version: "3.9"

services:

  alembic:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LAMINAR_POSTGRES_HOST: postgres
    command: alembic upgrade head
    networks:
      - laminar

  api:
    depends_on:
      - alembic
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LAMINAR_POSTGRES_HOST: postgres
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8081/healthz"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - laminar

  postgres:
    environment:
      POSTGRES_DB: laminar
      POSTGRES_PASSWORD: laminar
      POSTGRES_USER: laminar
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laminar"]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres
    networks:
      - laminar
    ports:
      - 5432:5432

networks:
  laminar:
    external: false
