[tool.black]
exclude = '''
(
  /(
    | \.venv
  )/
)
'''
line-length = 120
preview = true

[tool.coverage.report]
exclude_lines = [
  "pragma: not covered",
  "@overload",
]

[tool.flake8]
exclude = [
  ".venv",
]
ignore = [
  "E221",
  "E251",
  "W503",
  "E203",
]
max-complexity = 10
max-line-length = 120

[tool.isort]
line_length = 120
profile = "black"

[tool.mypy]
follow_imports = "silent"
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

strict = true

[tool.pytest.ini_options]
addopts = "-vv --durations 10 --failed-first --strict-markers"
markers = [
  "asyncio",
  "flow",
]
