"""empty message

Revision ID: fe53f2228262
Revises:
Create Date: 2021-01-24 16:37:50.570581

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fe53f2228262"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flow",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("project", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "execution",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("flow", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["flow"], ["flow.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "step",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("flow", sa.Integer(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["flow"], ["flow.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("execution", sa.Integer(), nullable=True),
        sa.Column("step", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["execution"], ["execution.id"]),
        sa.ForeignKeyConstraint(["step"], ["step.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("status")
    op.drop_table("step")
    op.drop_table("execution")
    op.drop_table("flow")
    # ### end Alembic commands ###
