name: integration
on: [push]

jobs:
  test:
    name: test ${{ matrix.os }} - 3.${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macOS]
        python-version: ['8', '9', '10', '11']
    env:
      PY_COLORS: '1'

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.${{ matrix.python-version }}
          architecture: x64

      - name: virtualenv
        run: make env

      - name: test
        run: make test

  build:
    name: build artifacts
    runs-on: ubuntu-latest
    needs: [test]
    env:
      PY_COLORS: '1'

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install
        run: make setup

      - name: build
        run: make build

      - name: check
        run: make check

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  promote:
    name: promote artifacts
    runs-on: ubuntu-latest
    needs: [build]
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    env:
      PY_COLORS: '1'

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: install
        run: make setup

      - name: check
        run: make check

      - name: tag
        run: make tag

      - name: promote
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
