name: integration
on: [push]
jobs:
  test:
    name: ${{ matrix.os }} - ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: ['3.8', '3.9', '3.10']
    env:
      PY_COLORS: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Virtualenv
        run: python -m pip install virtualenv && make env

      - name: Test
        run: . .venv/bin/activate && make test
